#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    TZ=${TZ}"
    echo "    DHCP_IF=${DHCP_IF}"
    echo "    DHCP_V6=${DHCP_V6}"
}

print_vars init-dhcp

# make our config dirs
mkdir -p /config

# Overlay config directory
mkdir -p /config/dhcp
if [ "${DHCP_V6}" = "true" ]; then
    cp -pn /etc/dhcp/dhcpd6.conf /config/dhcp/dhcpd6.conf
    test -e /data/dhcpd6.leases || touch /data/dhcpd6.leases
    chmod 664 /data/dhcpd6.leases
    chown abc:abc /data/dhcpd6.leases
else
    cp -pn /etc/dhcp/dhcpd.conf /config/dhcp/dhcpd.conf
    test -e /data/dhcpd.leases || touch /data/dhcpd.leases
    chmod 664 /data/dhcpd.leases
    chown abc:abc /data/dhcpd.leases
fi

