#!/usr/bin/with-contenv bash

print_vars () {
    if [ -n "${1}" ]; then
	title=" ${1}"
    else
	title=""
    fi
    echo "Environment${title}:"
    echo "    TZ=${TZ}"
    echo "    DHCP_IF=${DHCP_IF}"
}

print_vars

# make our config dirs
mkdir -p /config

# Overlay config directory
cp -rpn /etc/dhcp /config
test -e /data/dhcpd.leases || touch /data/dhcpd.leases

chmod 664 /data/dhcpd.leases
chown -R abc:abc \
	/data/dhcpd.leases

